<p>We have passed in the <code><a href="/wiki/Java_Programming/Keywords/try" title="Java Programming/Keywords/try"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">try</font></a></code> block until where the exception occurred and we have executed the <code><a href="/wiki/Java_Programming/Keywords/finally" title="Java Programming/Keywords/finally"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">finally</font></a></code> block. <b>NO CODE</b> after the try-catch block has been executed. If there is an exception that happens before the try-catch block, the <code><a href="/wiki/Java_Programming/Keywords/finally" title="Java Programming/Keywords/finally"><font style="color:DodgerBlue4; text-decoration: none; font-weight: bold;">finally</font></a></code> block is not executed.</p>