<p>As there is a thrown exception at line 5, the line 6 is not executed, but the exception is caught by the <code>catch</code> statement so the <code>catch</code> block is executed. The following code is also executed. Note that the <code>catch</code> statement takes an exception as parameter. There is a third case: when the exception is not from the same class as the parameter:</p>