<p>By default, when an exception is thrown, the current method is interrupted, the calling method is interrupted too and so on till the <code>main</code> method. A thrown exception can also be caught using a <code>try</code>/<code>catch</code> statement. Below is how a <code>try</code>/<code>catch</code> statement works:</p>