<p>A throwable contains a snapshot of the execution stack of its thread at the time it was created. It can also contain a message string that gives more information about the error. Finally, it can contain a cause: another throwable that caused this throwable to get thrown. The cause facility is also known as the <i>chained exception facility</i>, as the cause can, itself, have a cause, and so on, leading to a "chain" of exceptions, each caused by another.</p>